# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_amt',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_amt',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
