# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 14:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
    ]
